package br.edu.ifce.mflj.museu.Sino;


/**
* br/edu/ifce/mflj/museu/Sino/ISinoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sino.idl
* Monday, May 2, 2016 9:33:36 AM BRT
*/

public interface ISinoOperations 
{
  void noite (boolean noite);
} // interface ISinoOperations
